//! Conversation picker modal state, input handling, filtering, and rendering.

pub mod activate_selected_conversation;
pub mod apply_conversation_picker_query_change;
pub mod clamp_conversation_picker_selection;
pub mod close_conversation_picker;
pub mod collapse_selected_conversation_project;
pub mod conversation_picker_body;
pub mod conversation_picker_dialog_body_area;
pub mod conversation_picker_frame_area;
pub mod conversation_picker_item;
pub mod conversation_picker_item_position_at_row;
pub mod conversation_picker_items;
#[cfg(test)]
mod conversation_picker_items_tests;
pub mod conversation_picker_key_behavior;
pub mod conversation_picker_lines;
pub mod conversation_picker_mode;
pub mod conversation_picker_start_index;
pub mod conversation_picker_state;
pub mod current_conversation_picker_item_count;
pub mod filtered_conversation_indices;
pub mod focus_conversation_picker_end;
pub mod focus_conversation_picker_session;
pub mod focus_conversation_picker_start;
pub mod handle_conversation_picker_escape;
pub mod handle_conversation_picker_keyboard;
pub mod handle_conversation_picker_mouse;
pub mod matches_conversation_query;
pub mod move_conversation_picker_selection;
pub mod open_conversation_picker;
pub mod open_folder_conversation_picker;
pub mod open_place_in_active_split_picker;
pub mod open_selected_conversation_delete_confirmation;
pub mod open_selected_conversation_project;
pub mod render_conversation_picker_dialog;
pub mod reorder_selected_conversation;
pub mod selected_conversation_index;
pub mod selected_conversation_picker_item;
pub mod selected_conversation_picker_project_path;
pub mod toggle_selected_conversation_picker_item;
